=== ogyct/MessageProcessor/src/main/resources/xsd/address.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="address">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="address_id"/>
        <xs:element type="xs:string" name="address"/>
        <xs:element type="xs:string" name="address2"/>
        <xs:element type="xs:string" name="district"/>
        <xs:element type="xs:string" name="city_id"/>
        <xs:element type="xs:string" name="postal_code"/>
        <xs:element type="xs:string" name="phone"/>
        <xs:element type="xs:string" name="deleteYN"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ogyct/MessageProcessor/src/main/resources/xml/address.xml
<?xml version="1.0" encoding="UTF-8"?>
<address xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/address.xsd">
	<address_id>1</address_id>
	<address>Mira 27-19</address>
	<address2></address2>
	<district>mkr1</district>
	<city_id>Trekhgorny</city_id>
	<postal_code>456080</postal_code>
	<phone>69880</phone>
	<deleteYN>N</deleteYN>
</address>
